services:
  # sonarr
  Sonarr:
      container_name: Sonarr
      image: cr.hotio.dev/hotio/sonarr
      ports:
          - 8989:8989
      volumes:
          - /var/opt/servarr/config/sonarr:/config
          - /var/opt/servarr/data/sonarr:/data
      environment:
          - PUID=111
          - PGID=321
          - UMASK=002

  # radarr
  Radarr:
      container_name: Radarr
      image: cr.hotio.dev/hotio/radarr
      ports:
          - 7878:7878
      volumes:
          - /var/opt/servarr/config/radarr:/config
          - /var/opt/servarr/data/radarr:/data
      environment:
          - PUID=222
          - PGID=321
          - UMASK=002

  # bazarr
  Bazarr:
      container_name: Bazarr
      image: cr.hotio.dev/hotio/bazarr
      ports:
          - 6767:6767
      volumes:
          - /var/opt/servarr/config/bazarr:/config
          - /var/opt/servarr/data/bazarr:/data
      environment:
          - PUID=333
          - PGID=321
          - UMASK=002

  Jackett:
      container_name: Jackett
      image: cr.hotio.dev/hotio/jackett
      ports: 
          - 8117:9117
          #- 9117:9117
      volumes:
          - /var/opt/servarr/config/jackett:/config
          - /var/opt/servarr/data/jackett:/data
      environment:
          - PUID=444
          - PGID=321
          - UMASK=002

  # Transmission
  qBittorrent:
      container_name: qBittorrent
      image: cr.hotio.dev/hotio/qbittorrent
      ports:
          - 8080:8080
      volumes:
          - /var/opt/servarr/downloads
      environment:
          - PUID=555
          - PGID=321
          - UMASK=002

  # plex
  Plex:
      container_name: Plex
      image: cr.hotio.dev/hotio/plex
      ports:
          - 32400:32400
      volumes:
          - /var/opt/servarr/config/plex:/config
          - /var/opt/servarr/data/plex/media:/data/media
      environment:
          - PUID=666
          - PGID=321
          - UMASK=002